home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home),
    path('home/', views.home, name='home'),
    path('user_check/', views.user_check, name='user_check'),
]

polls/urls.py
from django.urls import path
from polls import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('download/', views.downloadFile, name='downloadFile'),
]

project_final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pre_diagnosis/', include('home.urls')),
    path('pre_diagnosis/question/', include('question.urls'))
]

question/urls.py
from django.urls import path
from . import views

app_name = 'question'

urlpatterns = [

    path('sick_part/<int:id>/', views.sick_part, name='sick_part'),
    path('sick_part/question_list/', views.question_list, name='question_list'),
    path('<int:question_id>/', views.single_question, name='single_question'),
    path('single_answer/', views.single_answer, name='single_answer'),
    path('next_question/', views.next_question, name='next_question')
]

testflow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

home/models.py
from django.db import models

# Create your models here.


# 환자 정보 테이블
class Patient(models.Model):
    patient_code = models.CharField(default="000000", max_length=6, blank=False, primary_key=True)
    name = models.CharField(max_length=10, blank=False)

    def __str__(self):
        return f'[{self.patient_code}] {self.name}'

# 사용자 테이블
class User(models.Model):
    patient_code = models.ForeignKey(Patient, on_delete=models.CASCADE)
    sick_parts = models.CharField(default="", max_length=100, null=True, blank=False)
    answer = models.TextField(default="", max_length=1000, blank=False)

    def __str__(self):
        return f'[{self.pk}] {self.patient_code}'

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

question/models.py
from django.db import models

# Create your models here.


# 부위 테이블
class Sickpart(models.Model):
    name = models.CharField(max_length=20, blank=False, primary_key=True)

    def __str__(self):
        return self.name


# 선지 테이블
class Option(models.Model):
    option = models.CharField(max_length=50, blank=False, primary_key=True)

    def __str__(self):
        return self.option


# 질문 테이블
class Question(models.Model):
    question = models.CharField(max_length=200, blank=False, unique=True)
    video = models.CharField(max_length=200, null=True)
    option = models.ForeignKey(Option, on_delete=models.RESTRICT)
    sick_part = models.ForeignKey(Sickpart, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.sick_part}] {self.question}'

home/views.py
from django.shortcuts import render
from home.models import User, Patient
from question.models import Question, Sickpart
from django.http import HttpResponseRedirect
from django.urls import reverse


# Create your views here.
def home(request):
    question = Question.objects.all()
    sickpart = Sickpart.objects.all()
    return render(request, 'home template/home.html', {'question':question, 'sickpart':sickpart})


def user_check(request):
    try:
        user = User()
        user.patient_code = Patient.objects.get(patient_code=request.POST['patient_code_'])
    except (KeyError, Patient.DoesNotExist):
        return render(request,'home template/home.html')
    else:
        user.save()
        return HttpResponseRedirect(reverse('question:sick_part', args=[user.pk]))

polls/views.py
import os

from django.shortcuts import render, get_object_or_404
from polls.models import Question, Choice
from django.http import HttpResponseRedirect, FileResponse
from django.urls import reverse
import csv


def index(request):
    latest_question_list = Question.objects.all()#.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'poll/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/detail.html', {'question': question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)

    #print(p)

    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
        #print(selected_choice)

        with open("output.csv", 'a') as file:
            fwriter = csv.writer(file)
            fwriter.writerow([p.question_text, selected_choice.choice_text])
        #    print(os.path.abspath("result.txt"))
        #file.close()

    except(KeyError, Choice.DoesNotExist):
        return render(request, 'poll/detail.html', {'question': p, 'error_message': "No answer selected."})
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'question': question})

def downloadFile(request):
    file_name = os.path.basename("output.csv")
    response = FileResponse(open(file_name, 'rb'), content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="result.csv"'

    return response

question/views.py
from django.shortcuts import render, get_object_or_404, redirect
from home.models import User
from question.models import Question, Sickpart, Option

from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.


def sick_part(request, id):
    global userid
    user = get_object_or_404(User, pk=id)
    userid = id

    sickparts = Sickpart.objects.all()
    return render(request, 'question template/sickparts.html', {'sickparts': sickparts})


def question_list(request):
    if request.POST:
        sick_part_list = request.POST.getlist('sick_part')
        sick_part_str = ','.join(sick_part_list)
        user = User.objects.get(pk=userid)
        user.sick_parts = sick_part_str
        user.save()

    global questions
    questions = []
    for sickpart in sick_part_list:
        question = Question.objects.filter(sick_part=sickpart)
        for q in question:
            questions.append(q)

    # return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
    return HttpResponseRedirect(reverse('question:next_question'))


def single_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    option = question.option
    option_ = option.option
    option_list = option_.split(',')
    return render(request, 'question template/question.html', {'question': question, 'option':option_list})


def single_answer(request):
    user = User.objects.get(pk=userid)
    user.answer = user.answer + ',' + request.POST['inlineRadioOptions']
    user.save()

    return HttpResponseRedirect(reverse('question:next_question'))

idx = 0
def next_question(request):
    global idx
    if idx < len(questions):
        q = questions[idx]

        idx += 1
        return HttpResponseRedirect(reverse('question:single_question', args=[q.pk]))
    else:
        exit()

home/templates/home template/home.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>
            (S)고령환자를 위한 예진 서비스(가제)
        </title>

        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="stylish/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet">
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'home/css/styles.css' %}">
    </head>
    <body>
        <a class="menu-toggle rounded " href="#">
            <i class="fas fa-bars"></i>
        </a>
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand" color="#fff">
                    더보기
                </li>
                <li class="sidebar-nav-item">
                    <a href="#introduction">
                        예진 서비스 사용방법
                    </a>
                </li>
                <li class="sidebar-nav-item">
                    <a href="#introduction">
                        어디가 아프세요?
                    </a>
                </li>
                <li class="sidebar-nav-item">
                    <a href="#introduction">
                        어떻게 아프신가요?
                    </a>
                </li><li class="sidebar-nav-item">
                    <a href="#introduction">
                        사회력이 있으신가요?
                    </a>
                </li>
            </ul>
        </nav>

        <!-- Header-->
        <header class="masthead d-flex align-items-center">
            <div class="container px-4 px-lg-5 text-center">
                <h1 class="mb-1">예진 서비스</h1>
                <h3 class="mb-5"><em>고령환자를 위한 정형외과 예진 서비스</em></h3>
                <a class="btn btn-primary btn-xl" href="#introduction">예진 시작하기</a>
            </div>
        </header>
        <!--Introduction-->
        <section class="content-section bg-light" id="introduction">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-10">
                        <div class="row gx-2 gx-lg-2 text-center">
                            <h3 class="my-5"><em>예진 서비스를 소개합니다.</em></h3>
                        </div>
                        <div class="row video-container">
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/F0EZghPeVLU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </div>
                        <div class="row gx-2 gx-lg-2 text-center">
                            <h3 class="my-5"><em>환자 코드를 입력해주세요.</em></h3>
                            <form action="{% url 'home:user_check' %}" method="post">
                                {% csrf_token %}
                                <div class="col text-center">
                                    <input type="text" name="patient_code_" class="form-control me-2 my-3" placeholder="000000">
                                    <input class="btn btn-primary btn-xl my-3" type="submit" value="예진 시작하기">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container px-4 px-lg-5">
                <p class="text-muted small mb-0">Copyright &copy; 고령환자를 위한 예진 서비스(가제) 2022</p>
            </div>
        </footer>

        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#"><i class="fas fa-angle-up"></i></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>

polls/templates/poll/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p>{{ error_message }</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">
        {{ choice.choice_text }}
    </label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
</body>
</html>

polls/templates/poll/downloadFile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Download</title>
</head>
<body>
    <div>
        <label>첨부 파일</label>
        	<form action="{% url 'excel:downloadFile'  %}">
        	<button type="submit">다운로드</button>
    		</form>
    </div>
</body>
</html>

polls/templates/poll/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
            <a href="/polls/{{ question.id }}">{{ question.question_text }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p> 설문이 없습니다. </p>
{% endif %}
</body>
</html>

polls/templates/poll/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again</a>
</body>
</html>

question/templates/question template/question.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>
            (Q_S)고령환자를 위한 예진 서비스(가제)
        </title>

        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="stylish/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet">
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'question/css/styles.css' %}">
    </head>
    <body>
        <a class="menu-toggle rounded " href="#">
            <i class="fas fa-bars"></i>
        </a>
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand" color="#fff">
                    더보기
                </li>
                <li class="sidebar-nav-item">
                    <a href="#introduction">
                        예진 서비스 사용방법
                    </a>
                </li>
                <li class="sidebar-nav-item">
                    <a href="#introduction">
                        어디가 아프세요?
                    </a>
                </li>
                <li class="sidebar-nav-item">
                    <a href="#introduction">
                        어떻게 아프신가요?
                    </a>
                </li><li class="sidebar-nav-item">
                    <a href="#introduction">
                        사회력이 있으신가요?
                    </a>
                </li>
            </ul>
        </nav>

        <!--Question-->
        <section class="content-section bg-light" id="question">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row justify-content-center">
                    <h1>{{ question.question }}</h1>
                </div>
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-10">
                        <div class="video-container mt-5">
                            <iframe width="560" height="315" src="{{ question.video }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!--Options-->
        <section class="content-section bg-light" id="options">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-10">
                         <form action="{% url 'question:single_answer' %}" method="post">
                            {% csrf_token %}
                            <div>
                                {% for opt in option %}
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="{{ opt }}" style="width:30px;height:30px;border:1px;background-color: #1D809F">
                                    <label class="form-check-label" for="inlineRadio1"  style="font-size:20pt;">{{ opt }}</label>
                                </div>
                                {% endfor %}
                            </div>
                            <input class="btn btn-primary btn-xl my-3" type="submit" value="다음 페이지">
                        </form>
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container px-4 px-lg-5">
                <p class="text-muted small mb-0">Copyright &copy; 고령환자를 위한 예진 서비스(가제) 2022</p>
            </div>
        </footer>

        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#"><i class="fas fa-angle-up"></i></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'question/js/scripts.js' %}"></script>
    </body>
</html>

question/templates/question template/sickparts.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>
            (Q_S)고령환자를 위한 예진 서비스(가제)
        </title>

        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="stylish/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet">
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'question/css/styles.css' %}">
    </head>
    <body>
        <a class="menu-toggle rounded " href="#">
            <i class="fas fa-bars"></i>
        </a>
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand" color="#fff">
                    더보기
                </li>
                <li class="sidebar-nav-item">
                    <a href="#introduction">
                        예진 서비스 사용방법
                    </a>
                </li>
                <li class="sidebar-nav-item">
                    <a href="#introduction">
                        어디가 아프세요?
                    </a>
                </li>
                <li class="sidebar-nav-item">
                    <a href="#introduction">
                        어떻게 아프신가요?
                    </a>
                </li><li class="sidebar-nav-item">
                    <a href="#introduction">
                        사회력이 있으신가요?
                    </a>
                </li>
            </ul>
        </nav>

        <!--Question-->
        <section class="content-section bg-light" id="question">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row justify-content-center">
                    <h1>[질문]어디가 아프신가요?</h1>
                </div>
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-10">
                        <div class="video-container mt-5">
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/h_o3JNK6AVs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!--Options-->
        <section class="content-section bg-light" id="options">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-10">
                         <form action="{% url 'question:question_list' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row px-2 my-2">
                                {% for sick_part in sickparts %}
                                <div class="col px-2 my-3 justify-content-center">
                                    <input type="checkbox" class="btn-check me-3" name="sick_part" value="{{sick_part.name}}" id="btn-check-outlined" autocomplete="off">
                                    <label class="btn btn-outline-primary me-3" for="btn-check-outlined">
                                        {{ sick_part.name }}
                                    </label>
                                    <br>
                                </div>
                                {% endfor %}
                            </div>
                             <input class="btn btn-primary btn-xl my-3" type="submit" value="다음 페이지">

                        </form>
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container px-4 px-lg-5">
                <p class="text-muted small mb-0">Copyright &copy; 고령환자를 위한 예진 서비스(가제) 2022</p>
            </div>
        </footer>

        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#"><i class="fas fa-angle-up"></i></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'question/js/scripts.js' %}"></script>
    </body>
</html>